# Cloud Build config: build & push image to Artifact Registry
# Usage:
# gcloud builds submit --config=cloudbuild.yaml --substitutions _REGION=us-central1,_REPOSITORY=moe-app,_IMAGE=moe-app

substitutions:
  _REGION: us-central1
  _REPOSITORY: moe-app
  _IMAGE: moe-app
  _TAG: manual

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build image'
    args: ['build','-t','${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}','.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push image'
    args: ['push','${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}']

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}'

