substitutions:
  _REGION: us-central1
  _REPOSITORY: moe-app
  _IMAGE: moe-router
  _TAG: manual

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build router image'
    args: ['build', '-f', 'Dockerfile', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push router image'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}']

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}'